### ISSUE TITLE
reason for symfony/cache 5

### ISSUE THREAD

**Issue by jGielen** [transip/transip-api-php#11]
is their a reason why you set it at symfony 5 and nog 3.4?

**Comment by dionbosschieter** [comment]
We did not think to much about this version pick, I guess we just choose the latest.

If the interface of the cache component is the same as 3.4 we could change it, perhaps it would be nicer to change the version back to 4.4 as this is a LTS release.

**Comment by jGielen** [comment]
and when will the support end for the soap client?

**Comment by jGielen** [comment]
3.4 is also in lts till end this year

**Comment by dionbosschieter** [comment]
We have tested with version 3.4 and 4.4 and these are indeed compatible.
So we released a new version (6.0.4) that allows the use of 3.4, 4.4 and 5.0 of the symfony/cache component. 
I hope this helps you out.

**Comment by jGielen** [comment]
yes it does Thanks :-)

**Comment by dionbosschieter** [comment]
As for the soap client support: last week we deployed a patch for that client so there is still some maintenance going on.
Although we marked the soap client as deprecated with the release of version 6.0, the soap client still functions and will remain so as we did not decide on a deadline to kill the soap API.

Even though this is still unclear we strongly recommend everyone to start porting their code to use the new ^6.0 client code :)
