### ISSUE TITLE
Updating HA-IP Pro - gets Error

### ISSUE THREAD

**Issue by petericebear** [transip/transip-api-php#13]
$haip = $api->haip()->getByName('name-of-the-hapi);
$haip->setHttpHealthCheckPort(80);
$haip->setHttpHealthCheckPath('/index.php');
$haip->setHttpHealthCheckSsl(false);
$api->haip()->update($haip);

Wanneer ik dit toepas dan krijg ik de error van:
Transip/Api/Library/Exception/HttpRequest/NotAcceptableException with message 'Error while applying config for Haip 'name-of-the-hapi'

Ik zag dat de poort een string is onderwater, ook als ik die even met de hand in een integer van de package aanpas dan geeft die alsnog deze zelfde fout. Enig idee?

**Comment by petericebear** [comment]
Standaard staat de checkmethod op TCP. Wanneer deze veranderd is dan werkt bovenstaande code wel. Er mist nog een methode om de Method op te geven/uit te lezen van de Method TCP/HTTP.

Als die method er komt dan is het issue opgelost.

**Comment by petericebear** [comment]
Is hier ook een update voor?

**Comment by kavash** [comment]
Dit probleem is inmiddels opgelost
