### ISSUE TITLE
Webhook voor domein updates

### ISSUE THREAD

**Issue by websmurf** [transip/transip-api-php#15]
Heb er nog niets over gevonden in de documentatie, maar wordt het in de toekomst mogelijk om in te haken op een domein update? 

Op dit moment wordt er namelijk een mail verstuurd (bijvoorbeeld contactwijziging, dns wijziging, uitgaande verhuizing etc), maar die zijn wat lastig geautomatiseerd af te handelen.

Het zou handig zijn als je bijvoorbeeld met een webhook subscription hier een stuk automatisering aan kunt verbinden (zoals bijvoorbeeld [Exact Online](https://support.exactonline.com/community/s/knowledge-base#All-All-DNO-Content-webhooksc) dit ook mogelijk maakt)

**Comment by kavash** [comment]
Er zijn op dit moment helaas nog geen plannen om iets soortgelijks te implementeren.
