### ISSUE TITLE
PHP8 niet ondersteund, Guzzle error

### ISSUE THREAD

**Issue by ronaldcornet** [transip/transip-api-php#28]
Na veel proberen kom ik erachter dat PHP8 niet werkt.
Het geeft deze fout:
Next Transip\Api\Library\Exception\HttpClientException: Generic HTTP Client Exception: Connection refused for URI https://api.transip.nl/v6/auth in /home/ronald/vendor/transip/transip-api-php/src/Exception/HttpClientException.php:22
Stack trace:
#0 /home/ronald/vendor/transip/transip-api-php/src/HttpClient/GuzzleClient.php(272): Transip\Api\Library\Exception\HttpClientException::genericRequestException()
#1 /home/ronald/vendor/transip/transip-api-php/src/HttpClient/GuzzleClient.php(175): Transip\Api\Library\HttpClient\GuzzleClient->handleException()
#2 /home/ronald/vendor/transip/transip-api-php/src/Repository/AuthRepository.php(47): Transip\Api\Library\HttpClient\GuzzleClient->postAuthentication()
#3 /home/ronald/vendor/transip/transip-api-php/src/HttpClient/HttpClient.php(103): Transip\Api\Library\Repository\AuthRepository->createToken()
#4 /home/ronald/vendor/transip/transip-api-php/src/HttpClient/GuzzleClient.php(72): Transip\Api\Library\HttpClient\HttpClient->checkAndRenewToken()
#5 /home/ronald/vendor/transip/transip-api-php/src/HttpClient/GuzzleClient.php(55): Transip\Api\Library\HttpClient\GuzzleClient->request()
#6 /home/ronald/vendor/transip/transip-api-php/src/HttpClient/GuzzleClient.php(89): Transip\Api\Library\HttpClient\GuzzleClient->sendRequest()
#7 /home/ronald/vendor/transip/transip-api-php/src/Repository/ApiTestRepository.php(11): Transip\Api\Library\HttpClient\GuzzleClient->get()
#8 /home/ronald/transiptest.php(50): Transip\Api\Library\Repository\ApiTestRepository->test()
#9 {main}
  thrown in /home/ronald/vendor/transip/transip-api-php/src/Exception/HttpClientException.php on line 22

Ik vind meer info over GuzzleClient en gebrek aan compatibiliteit met PHP8.
Is er een oplossing die dit wel ondersteunt?

**Comment by xvilo** [comment]
It should work fine on PHP 8 and above (the error would hint at a networking issue), can you share the following output with us with some more debug information?
```sh
composer info guzzlehttp/guzzle
composer info transip/transip-api-php
php -v
```

It's also possible to use a [PSR-18 compatible client](https://packagist.org/providers/psr/http-client-implementation), but that's currently not the default due to backwards compatibility reasons. You can use the `\Transip\Api\Library\HttpClient\HttpMethodsClient()` client for that. 
```php
<?php

include 'vendor/autoload.php';

use Transip\Api\Library\HttpClient\Builder\ClientBuilder;
use Transip\Api\Library\HttpClient\HttpMethodsClient;
use Transip\Api\Library\TransipAPI;

$httpClient = new HttpMethodsClient(new ClientBuilder(
    // It can detect compatible PSR-18 HttpClients, however, it can be set explicitly
));
$transipApi = new TransipAPI(
    customerLoginName: 'username',
    privateKey: '--- key here ---',
    httpClient: $httpClient
);
```

**Comment by ronaldcornet** [comment]
Dank voor de snelle reactie! Ik heb de alternatieve code geprobeerd, maar die geeft eenzelfde connection refused error.

**Comment by xvilo** [comment]
Kan je buiten de code om, ook verbinden met de API? Bijvoorbeeld als je `curl https://api.transip.nl/v6/auth -v` doet?

**Comment by ronaldcornet** [comment]
Ja, dat werkt, ik krijg inderdaad die melding.
Ik heb op dezelfde machine een docker container opgezet met PHP7, en daarin werkt de transip-test code probleemloos. Dat was de reden voor m'n melding. Ik dacht eerst dat ik niet de goede key gebruikte, of combi met whitelisting, maar het enige verschil is nu PHP8 native, wat niet werkt, of php7 in docker, wat wel werkt.

**Comment by xvilo** [comment]
Om alles uit te sluiten, kun je het met PHP 8, _in Docker_ proberen?

**Comment by ronaldcornet** [comment]
Ah, goeie tip! Dan werkt het wel. Ik zal de info-commands die je hierboven gaf ook in de docker draaien om een vergelijkend warenonderzoek te doen. Blijkbaar zit er ergens een verschil tussen de versies die in docker worden geinstalleerd, en de versie die lokaal zijn of worden geïnstalleerd.

**Comment by ronaldcornet** [comment]
Fijn voor jullie 🤣, maar niet voor mij ... 😉
Dank voor de support, ik ga verder stoeien, en wijk intussen even uit naar een machine zonder php waar ik v7 neerzet.
