### ISSUE TITLE
Webhosting available in API

### ISSUE THREAD

**Issue by erikkraijenoord** [transip/transip-api-php#29]
Hi,

We have been waiting for a few months to see if `webhosting` will be available in the API, but on the recent update we only see `kubernetes` as experimental product. Does TransIP have the intention to add webhosting to the API and on what timespan could we expect this to happen? This would determine if we are planning to park our domains at TransIP because webhosting requires the domains to be available in TransIP.

If this would not be an option (no is also a answer) we can transfer our thoughts to something else.

> https://api.transip.nl/rest/docs.html

----

Q 1: Will webhosting be added to the API?
Q 2: If 1 is a yes, what timespan would this be available?

**Comment by svenwiltink** [comment]
There are currently no plans to add webhosting to the API.
