### ISSUE TITLE
dns entry toevoegen

### ISSUE THREAD

**Issue by xciser77** [transip/transip-api-php#4]
misschien handig om te vermelden dat je via de php library (of api) niet slechts 1 entry kunt toevoegen. Als je dat doet dan verwijderd ie alle overige dns entries en heb je alleen de enties van je api script

**Comment by RobinGeuze** [comment]
De documentatie geeft exact dit al aan, en het staat ook in de docblock bij de setDnsEntries functie, zie:
https://api.transip.nl/docs/transip.nl/class-Transip_DnsService.html#_setDnsEntries
